language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install unittest2 flake8
  - pip install coveralls
  - pip install requests
  - pip install requests_mock
  - python setup.py install
script:
  - flake8 onfido
  - python -W always setup.py test
  - coverage run --source=onfido setup.py test
after_success:
  - coveralls